apiVersion: v1
kind: ConfigMap
metadata:
  name: react-master-amitsharma09
  namespace: kubernetes-cluster-amitsharma09
  labels:
    app: react-master-amitsharma09
data:
  API_URL: "http://google.com"
  ENVIRONMENT: "Dev"
  LANGUAGE: "English"

---

apiVersion: v1
kind: Secret
metadata:
  name: react-master-amitsharma09
  namespace: kubernetes-cluster-amitsharma09
data:
  DB_PASSWORD: "password"
  USER_PASSWORD: "cGFzc3dvcmQ="
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-master-amitsharma09-deployment
  namespace: kubernetes-cluster-amitsharma09
  labels:
    app: react-master-amitsharma09
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-master-amitsharma09
  template:
    metadata:
      labels:
        app: react-master-amitsharma09
    spec:
      containers:
        - name: react-master-amitsharma09
          image: nagpdevopsfinal/i-amitsharma09-frontend:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: react-master-amitsharma09
            - secretRef:
                name: react-master-amitsharma09
---
apiVersion: v1
kind: Service
metadata:
  name: react-master-amitsharma09
  namespace: kubernetes-cluster-amitsharma09
spec:
  type: LoadBalancer
  selector:
    app: react-master-amitsharma09
  ports:
  - targetPort: 3000
    port: 3000
    protocol: TCP